server:
  port: 800    #포트번호 설정
  servlet:
    context-path: /   #경로 혹은 요청설정..? @GetMapping("/test/1") return "/returnPage"
    encoding:
      charset: utf-8   #언어설정
      enabled: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/      #view resolver라는 설정인데 경로는 이렇고
      suffix: .jsp                 #.jsp파일로 응답하겠다는거임. xml, yml, html 등등
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver                              #mariadb 사용하겠다는 드라이버 설정
    url: jdbc:mariadb://localhost:3306/photogram?serverTimezone=Asia/Seoul  #mariadb url값
    username: cos
    password: cos1234
    
  jpa:                    #jpa 설정
    open-in-view: true    #단어가 너무 어려우니 다시 공부 필요
    hibernate:
      ddl-auto: update    #서버가 재가동 될때마다 데이터를 다 drop함 (update와
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Table, Column 명칭 전략
    show-sql: true        #sql문이 나가면 콘솔창에 출력해줌
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234

# Unable to start LiveReload server 에러 해결법인데 안됨
    devtools:
      livereload:
        enabled: false



file:
  path: C:/workspace/springbootwork/upload/
